apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: omergal/digital-envelope-server
          envFrom:
            - configMapRef:
                name: postgres-config
          env:
            - name: CLIENT_ID
              value: "277026531583-scjcgic2kb81fa6b76mljrn523e77lca.apps.googleusercontent.com"
            - name: DATABASE_URL
              value: "postgres://root:password@postgres-srv:5432/digital-envelope?sslmode=disable"
            - name: SESSION_SECRET
              value: "abcde"
            - name: CLIENT_SECRET
              value: "bbcdee"
            - name: COOKIE_KEY
              value: "abbcs"
            #   valueFrom:
            #     secretKeyRef:
            #       name: session-secret
            #       key: session-secret
            # - name: COOKIE_KEY
            #   value: ASJKKkasdSSaasLLlMM
            # - name: CLIENT_SECRET
            #   valueFrom:
            #     secretKeyRef:
            #       name: google-secret
            #       key: client-secret
---
apiVersion: v1
kind: Service
metadata:
  name: server-srv
spec:
  selector:
    app: server
  ports:
    - name: server
      protocol: TCP
      port: 3000
      targetPort: 3000
