apiVersion: apps/v1
kind: Deployment
metadata:
  name: de-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: de
  template:
    metadata:
      labels:
        app: de
    spec:
      containers:
        - name: de
          image: omergal/digital-envelope-server
          env:
            - name: CLIENT_ID
              value: "277026531583-scjcgic2kb81fa6b76mljrn523e77lca.apps.googleusercontent.com"
            - name: DATABASE_URL
              value: "postgres://grthhtioyrvogb:2fb1e6c445c3deb6361721a65f102981145342925d0e05b5d7896033e9f37553@ec2-176-34-215-248.eu-west-1.compute.amazonaws.com:5432/dd031li88imtq6"
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: session-secret
                  key: SESSION_SECRET
            - name: COOKIE_KEY
              value: ASJKKkasdSSaasLLlMM
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-secret
                  key: CLIENT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: de-srv
spec:
  selector:
    app: de
  ports:
    - name: de
      protocol: TCP
      port: 3000
      targetPort: 3000
