apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: omergal/digital-envelope-server
          envFrom:
            - configMapRef:
                name: postgres-config
          env:
            - name: CLIENT_ID
              value: 277026531583-scjcgic2kb81fa6b76mljrn523e77lca.apps.googleusercontent.com
            - name: DATABASE_URL
              value: postgres://root:password@postgres-srv:5432/digital-envelope
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: session-secret
                  key: SESSION_SECRET
            - name: COOKIE_KEY
              value: ASJKKkasdSSaasLLlMM
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-secret
                  key: CLIENT_SECRET
            - name: STRIPE_SECRET
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_SECRET
            - name: STRIPE_CLIENT
              value: pk_test_51L7i4RGHAMj9Boauziuk9EFyiXAzPsv7RWE1ZWBsF6dtEG77WnbbdGmUyE1cyuAfa5oMBHnm41efExk7KU3sAR3p00lv4rPKFn
---
apiVersion: v1
kind: Service
metadata:
  name: server-srv
spec:
  selector:
    app: server
  ports:
    - name: server
      protocol: TCP
      port: 3000
      targetPort: 3000
